// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLB_JLXGta2v2e8APcMn_5pFnZ2AEryY',
    appId: '1:958602574835:android:d0a7905c3d5f51b44df086',
    messagingSenderId: '958602574835',
    projectId: 'lifelinkplus-40efc',
    authDomain: 'lifelinkplus-40efc.firebaseapp.com',
    storageBucket: 'lifelinkplus-40efc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpLB_JLXGta2v2e8APcMn_5pFnZ2AEryY',
    appId: '1:958602574835:android:d0a7905c3d5f51b44df086',
    messagingSenderId: '958602574835',
    projectId: 'lifelinkplus-40efc',
    storageBucket: 'lifelinkplus-40efc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpLB_JLXGta2v2e8APcMn_5pFnZ2AEryY',
    appId: '1:958602574835:android:d0a7905c3d5f51b44df086',
    messagingSenderId: '958602574835',
    projectId: 'lifelinkplus-40efc',
    storageBucket: 'lifelinkplus-40efc.firebasestorage.app',
    iosClientId: '958602574835-gkjb2e72vjvii5vvni4amn70ftl7tmbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpLB_JLXGta2v2e8APcMn_5pFnZ2AEryY',
    appId: '1:958602574835:android:d0a7905c3d5f51b44df086',
    messagingSenderId: '958602574835',
    projectId: 'lifelinkplus-40efc',
    storageBucket: 'lifelinkplus-40efc.firebasestorage.app',
    iosClientId: '958602574835-gkjb2e72vjvii5vvni4amn70ftl7tmbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifelink',
  );
} 